### ISSUE TITLE
运行出错 

### ISSUE THREAD

**Issue by Genicur** [Mythologyli/jd-price-check#4]
[root@VM-8-2-centos ~]# python /root/jd-price-check/main.py
Traceback (most recent call last):
  File "/root/jd-price-check/main.py", line 119, in <module>
    main()
  File "/root/jd-price-check/main.py", line 105, in main
    with open('config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

[root@VM-8-2-centos ~]# cd /root/jd-price-check

[root@VM-8-2-centos jd-price-check]# python main.py
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 106, in main
    config = json.load(f)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 22 (char 38)

**Comment by Mythologyli** [comment]
参考 README，需要在 main.py 的同目录下新建 config.json 文件，并**删除 // 及后面的文字**
如果已经有 config.json 但仍然出错，请附上 config.json 的内容

**Comment by Genicur** [comment]
> 参考 README，需要在 main.py 的同目录下新建 config.json 文件，并**删除 // 及后面的文字** 如果已经有 config.json 但仍然出错，请附上 config.json 的内容

sory 我不小心多删了个, 现在已经运行正常了 我想问一下 这种无货下架有货上架的商品可以监控吗？ https://item.jd.com/100016148864.html

**Comment by Mythologyli** [comment]
> > 参考 README，需要在 main.py 的同目录下新建 config.json 文件，并**删除 // 及后面的文字** 如果已经有 config.json 但仍然出错，请附上 config.json 的内容
> 
> sory 我不小心多删了个, 现在已经运行正常了 我想问一下 这种无货下架有货上架的商品可以监控吗？ https://item.jd.com/100016148864.html

现在这个脚本不行，要买的东西已经买到了，暂时没有时间开发

**Comment by Genicur** [comment]
cron定时过短是否会被京东ban？
或者您使用的时候cron定时多少

**Comment by Mythologyli** [comment]
> cron定时过短是否会被京东ban？ 或者您使用的时候cron定时多少

会的，我是 1 小时一次

**Comment by Genicur** [comment]
> > cron定时过短是否会被京东ban？ 或者您使用的时候cron定时多少
> 
> 会的，我是 1 小时一次

谢谢
